export const booking = {
  planNames: {
    hourly: "시간제",
    daily: "일일 요금제",
    mini: "미니",
    strand: "스트랜드",
    longstay: "장기 보관",
    custom: "맞춤",
  },
  planDurations: {
    hourly: "최소 1시간",
    daily: "최대 24시간",
    mini: "최대 1주일",
    strand: "최대 1개월",
    longstay: "최대 4개월",
    custom: "원하는 기간",
  },
  planTopBadge: "TOP",

  laneFlexible: "자유 요금제",
  laneFlatRate: "고정 요금제",
  laneFlexibleSub: "관광객 및 워크인 고객용",
  laneFlatRateSub: "주재원 및 디지털 노마드용",
  laneCustom: "맞춤 요금",
  laneCustomSub: "원하는 기간으로 보관",
  customPrice: "최저가",

  planLabel: "요금제",
  planPlaceholder: "요금제를 선택하세요",
  planFirstHint: "먼저 요금제를 선택한 후 나머지를 입력해 주세요.",

  contactTitle: "연락처 정보",

  dropOffDateLabel: "맡기는 날짜",
  pickupDateLabel: "픽업 날짜",
  dateWord: "날짜",
  timeWord: "시간",
  prevMonthLabel: "이전 달",
  nextMonthLabel: "다음 달",
  sameDayNote: "시간제는 당일 픽업만 가능합니다.",
  pickupFirstNote: "먼저 맡기는 날짜와 시간을 선택하세요.",
  latestPickupPrefix: "이 요금제의 마지막 픽업 시간: ",
  customHint: "선택하신 기간에 가장 저렴한 요금제 조합으로 계산합니다.",
  bagsLabel: "가방 수",
  bagsHelp: "가방 수 = 보관 물품 개수 (인원 수 아님)",
  decreaseLabel: "줄이기",
  increaseLabel: "늘리기",

  /* Korean doesn't pluralize nouns — singular and plural are the same word. */
  hourUnit: { singular: "시간", plural: "시간" },
  dayUnit: { singular: "일", plural: "일" },
  bagUnit: { singular: "개", plural: "개" },
  weekUnit: { singular: "주", plural: "주" },
  monthUnit: { singular: "개월", plural: "개월" },

  nameLabel: "이름",
  namePlaceholder: "성함을 입력하세요",
  whatsappLabel: "WhatsApp",
  whatsappPlaceholder: "전화번호",
  phoneCountryLabel: "국가 번호",
  phoneCountrySearch: "국가 또는 번호 검색",
  phoneCountryEmpty: "국가를 찾을 수 없습니다",
  emailLabel: "이메일",
  emailPlaceholder: "you@example.com",

  oversizedHelpPrefix: "28인치 이상, 자전거, 서프보드 · +",
  perDayLabel: "1일당",
  perPeriodLabel: "1주 · 1개월 · 4개월 요금제당",
  oversizedCountLabel: "초과 크기 짐",
  oversizedTipLabel: "초과 크기 기준 안내",
  oversizedTipBody:
    "초과 크기는 28인치(71cm) 이상의 캐리어, 자전거, 서프보드, 큰 박스를 말합니다. 초과 크기 짐은 추가 요금이 있습니다.",
  noSlotsTodayNotice: "오늘 남은 시간대가 없습니다. 다른 맡기는 날짜를 선택하세요.",
  noLaterSlotsNotice: "더 늦은 시간대가 없습니다. 맡기는 시간을 앞당겨 주세요.",
  invalidPhone: "올바른 전화번호를 입력하세요",
  successOpenWhatsApp: "WhatsApp 열기",
  successWhatsAppHint: "WhatsApp이 열리지 않았나요? 눌러서 예약을 보내세요.",

  totalLabel: "총액",
  totalFlatFee: "총액 (고정 요금)",
  totalPrefix: "총액 (",
  totalSuffix: ")",
  /* 합계 아래의 요금 계산 내역(영수증). 고객이 직접 확인할 수 있도록 모든 계산
     단계를 보여줍니다. {자리표시자}는 PriceBreakdown이 채웁니다. (임시 번역) */
  receiptTitle: "요금 계산 방식",
  receiptEmpty: "날짜를 선택하면 요금의 모든 계산 단계가 여기에 표시됩니다.",
  receiptStorage: "보관 요금 (가방 1개 기준)",
  receiptOversized: "초과 크기 추가 요금 (초과 크기 짐 1개 기준)",
  receiptPerBag: "가방 1개 요금",
  receiptPerOversizedBag: "초과 크기 짐 1개 추가 요금",
  receiptOversizedBagUnit: { singular: "초과 크기 짐", plural: "초과 크기 짐" },
  receiptOnce: "시간 수와 관계없이 1회만 부과",
  receiptCapped: "{hours}시간이 넘으면 1일 요금으로 제한",
  receiptTotal: "합계",
  receiptNoteCustom: "맞춤 요금은 선택하신 기간을 모두 포함하는 가장 저렴한 요금제 조합으로 계산합니다.",
  receiptNoteCompare: "참고: {days}일을 1일 요금으로만 계산하면 가방 1개당 {price}입니다.",
  receiptNoteLastPeriod: "마지막 기간은 {date}까지입니다. 더 일찍 찾아가셔도 전체 기간 요금을 내셔야 합니다.",
  receiptNoteFlat: "정액 요금 하나로 전체 기간을 이용할 수 있습니다. 일찍 찾아가셔도 요금은 줄지 않습니다.",
  receiptNoteDays: "1일은 맡기신 시각부터 24시간입니다. 각 기간이 끝난 뒤 {minutes}분의 유예 시간을 드립니다.",
  receiptNoteHourly: "시작한 1시간마다 {price}입니다. {hours}시간이 넘으면 1일 요금이 더 저렴하므로 1일 요금으로 계산합니다.",


  consentAgreedText: "이용약관 및 개인정보처리방침에 동의함",
  changeLabel: "변경",
  consentPromptPre: "스토우의 ",
  consentPromptTos: "이용약관",
  consentPromptAnd: " 및 ",
  consentPromptPrivacy: "개인정보처리방침",
  consentPromptPost: "을 확인하고 동의해야 계속할 수 있습니다",
  consentErrorText: "계속하려면 확인 후 동의해 주세요",

  submitLoading: "WhatsApp 여는 중…",
  submitIdle: "WhatsApp으로 예약 확정",

  successTitle: "요청이 전송되었습니다!",
  successSubtitle: "예약 정보가 WhatsApp에 전달되었습니다.",
  successReplyTime: "15분 이내에 답변드립니다.",
  successRefPrefix: "예약번호: ",
  policyEmailLabel: "약관 동의 확인 이메일",
  emailSendingPrefix: "전송 중: ",
  emailSentPrefix: "전송 완료: ",
  emailFailedFallback: "전송 실패",
  emailWillSendPrefix: "전송 예정: ",
  retryLabel: "다시 시도",
  backToHome: "홈으로 돌아가기",
  bookAgain: "다시 예약하기",

  required: "필수 입력",
  invalidEmail: "올바르지 않은 이메일",
  dateInPast: "오늘 또는 이후 날짜를 선택하세요",
  pickupBeforeDropOff: "픽업은 맡기는 시간보다 늦어야 합니다",
  pickupOutsidePlan: "이 요금제의 픽업 가능 시간을 벗어났습니다",
} as const;
