export const booking = {
  planNames: {
    hourly: "時間単位",
    daily: "1日単位",
    mini: "ミニ",
    strand: "ストランド",
    longstay: "長期",
    custom: "カスタム",
  },
  planDurations: {
    hourly: "最低1時間",
    daily: "最大24時間",
    mini: "最大1週間",
    strand: "最大1か月",
    longstay: "最大4か月",
    custom: "自由な期間",
  },
  planTopBadge: "TOP",

  laneFlexible: "フレキシブル",
  laneFlatRate: "定額",
  laneFlexibleSub: "観光・当日ご来店の方に",
  laneFlatRateSub: "駐在員・デジタルノマドの方に",
  laneCustom: "カスタム",
  laneCustomSub: "好きな期間で",
  customPrice: "最安価格",

  planLabel: "料金プラン",
  planPlaceholder: "プランを選択してください",
  planFirstHint: "まずプランを選択してから、残りの項目を入力してください。",

  contactTitle: "ご連絡先",

  dropOffDateLabel: "預ける日",
  pickupDateLabel: "受け取り日",
  dateWord: "日付",
  timeWord: "時間",
  prevMonthLabel: "前の月",
  nextMonthLabel: "次の月",
  sameDayNote: "時間単位は当日のお受け取りのみです。",
  pickupFirstNote: "まず預ける日時を選択してください。",
  latestPickupPrefix: "このプランの最終受け取り: ",
  customHint: "ご指定の期間に対し、最も安いプランの組み合わせで計算します。",
  bagsLabel: "個数",
  bagsHelp: "個数 = お預かりする荷物の数（人数ではありません）",
  decreaseLabel: "減らす",
  increaseLabel: "増やす",

  /* Japanese doesn't pluralize nouns — singular and plural are identical. */
  hourUnit: { singular: "時間", plural: "時間" },
  dayUnit: { singular: "日", plural: "日" },
  bagUnit: { singular: "個", plural: "個" },
  weekUnit: { singular: "週間", plural: "週間" },
  monthUnit: { singular: "か月", plural: "か月" },

  nameLabel: "お名前",
  namePlaceholder: "お名前をご入力ください",
  whatsappLabel: "WhatsApp",
  whatsappPlaceholder: "電話番号",
  phoneCountryLabel: "国番号",
  phoneCountrySearch: "国名または番号で検索",
  phoneCountryEmpty: "該当する国がありません",
  emailLabel: "メールアドレス",
  emailPlaceholder: "you@example.com",

  oversizedHelpPrefix: "28インチ以上、自転車、サーフボード · +",
  perDayLabel: "1日あたり",
  perPeriodLabel: "1週間・1か月・4か月プランごと",
  oversizedCountLabel: "サイズ超過の荷物",
  oversizedTipLabel: "サイズ超過の基準について",
  oversizedTipBody:
    "サイズ超過とは、28インチ（71cm）以上のスーツケース、自転車、サーフボード、大きな箱のことです。サイズ超過の荷物は追加料金がかかります。",
  noSlotsTodayNotice: "本日の時間枠はもうありません。別の預け入れ日をお選びください。",
  noLaterSlotsNotice: "これより遅い枠がありません。預け入れ時間を早めてください。",
  invalidPhone: "有効な電話番号を入力してください",
  successOpenWhatsApp: "WhatsAppを開く",
  successWhatsAppHint: "WhatsAppが開きませんでしたか？タップして予約を送信してください。",

  totalLabel: "合計",
  totalFlatFee: "合計（定額）",
  totalPrefix: "合計（",
  totalSuffix: "）",
  /* 合計の下に表示する料金の計算内訳（レシート）。お客様ご自身で確認できるよう、
     計算の全ステップを示します。{プレースホルダー}は PriceBreakdown が埋めます。（暫定訳） */
  receiptTitle: "料金の計算方法",
  receiptEmpty: "日付を選ぶと、料金の計算手順がすべてここに表示されます。",
  receiptStorage: "保管料（荷物1個あたり）",
  receiptOversized: "サイズ超過の追加料金（超過荷物1個あたり）",
  receiptPerBag: "荷物1個の料金",
  receiptPerOversizedBag: "超過荷物1個の追加料金",
  receiptOversizedBagUnit: { singular: "超過荷物", plural: "超過荷物" },
  receiptOnce: "時間数に関わらず1回のみ",
  receiptCapped: "{hours}時間を超えると1日料金が上限",
  receiptTotal: "合計",
  receiptNoteCustom: "カスタムは、ご指定の期間をすべてカバーする最も安いプランの組み合わせで計算します。",
  receiptNoteCompare: "参考：{days}日を1日料金だけで計算すると、荷物1個あたり{price}です。",
  receiptNoteLastPeriod: "最後の期間は{date}までです。早めにお受け取りいただいても、期間全体の料金をお支払いいただきます。",
  receiptNoteFlat: "1つの定額料金で期間全体をご利用いただけます。早めにお受け取りいただいても料金は変わりません。",
  receiptNoteDays: "1日は、お預けの時刻から24時間です。各期間の終了後に{minutes}分の猶予があります。",
  receiptNoteHourly: "開始した1時間ごとに{price}です。{hours}時間を超えると1日料金のほうが安くなるため、1日料金で計算します。",


  consentAgreedText: "利用規約およびプライバシーポリシーに同意済み",
  changeLabel: "変更",
  consentPromptPre: "Stowの",
  consentPromptTos: "利用規約",
  consentPromptAnd: "および",
  consentPromptPrivacy: "プライバシーポリシー",
  consentPromptPost: "をご確認・ご同意のうえお進みください",
  consentErrorText: "続行するにはご確認とご同意をお願いします",

  submitLoading: "WhatsAppを開いています…",
  submitIdle: "WhatsAppで予約を確定",

  successTitle: "送信しました！",
  successSubtitle: "ご予約内容がWhatsAppに送信されました。",
  successReplyTime: "15分以内にお返事します。",
  successRefPrefix: "予約番号: ",
  policyEmailLabel: "規約同意の確認メール",
  emailSendingPrefix: "送信中: ",
  emailSentPrefix: "送信済み: ",
  emailFailedFallback: "送信に失敗しました",
  emailWillSendPrefix: "送信予定: ",
  retryLabel: "再試行",
  backToHome: "ホームに戻る",
  bookAgain: "もう一度予約する",

  required: "必須",
  invalidEmail: "メールアドレスが正しくありません",
  dateInPast: "本日以降の日付をお選びください",
  pickupBeforeDropOff: "受け取りは預ける時間より後にしてください",
  pickupOutsidePlan: "このプランの受け取り可能時間外です",
} as const;
